name: cherrypick
description: Experimental Dependency Injection library.
version: 0.1.1
homepage: https://github.com/pese-git/cherrypick
documentation: https://github.com/pese-git/cherrypick/wiki
repository: https://github.com/pese-git/cherrypick
issue_tracker: https://github.com/pese-git/cherrypick/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8

  mockito: ^5.0.3
