name: cherrypick
description: Cherrypick is a small dependency injection (DI) library for dart/flutter projects.
version: 0.1.1+2
homepage: https://github.com/pese-git/cherrypick
documentation: https://github.com/pese-git/cherrypick/wiki
repository: https://github.com/pese-git/cherrypick
issue_tracker: https://github.com/pese-git/cherrypick/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0

  test: ^1.17.2

  mockito: ^5.0.6
