name: dart_di
description: Experimental Dependency Injection library.
version: 0.0.1
author: Sergey Penkovsky <sergey.penkovsky@gmail.com>
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  test: ^1.14.3

  mockito: ^4.1.1% 
